before_script:
    - . ~/.nvm/nvm.sh
    - nvm use 10.15.0

stages:
    - test
    - deploy
    - run

test:
    stage: test
    script:
        - ./mvnw clean test
        - npm test

deploy_Release:
    stage: deploy
    script:
        - chmod 777 -R ./
        - rsync -rlDv -q --delete ./ /home/rigo/gpsapp
        - ./mvnw clean package -DskipTests
    artifacts:
        paths:
            - target/
    environment:
        name: Release
        url: 50.116.45.115:8080
    only:
        - Release

deploy_master:
    stage: deploy
    script:
        - chmod 777 -R ./
        - rsync -rlDv -q --delete ./ /home/rigo/gpsapp
        - ./mvnw clean package -DskipTests
    artifacts:
        paths:
            - target/
    environment:
        name: master
        url: 50.116.45.115:9090
    only:
        - master

run_Release:
    stage: run
    script:
        - nohup sh ./scripts/startMVNdev.sh &
    environment:
        name: Release
        url: 50.116.45.115:8080
    only:
        - Release

run_master:
    stage: run
    script:
        - nohup sh ./scripts/startMVN.sh &
    environment:
        name: master
        url: 50.116.45.115:9090
    only:
        - master
