before_script:
    - . ~/.nvm/nvm.sh
    - nvm use 10.15.0

stages:
    - test
    - deploy

deploy_Release:
    stage: deploy
    script:
        - chmod 777 -R ./
        - rsync -rlDv -q --delete ./ /home/rigo/gpsapp
        - ./mvnw clean package -DskipTests
        - sh scripts/startMVNdev.sh
        - exit
    environment:
        name: Release
        url: 50.116.45.115:8080
    only:
        - Release

deploy_master:
    stage: deploy
    script:
        - chmod 777 -R ./
        - rsync -rlDv -q --delete ./ /home/rigo/gpsapp
        - SPRING_PROFILES_ACTIVE=prod ./mvnw -Pprod clean package -DskipTests
        - sh scripts/startMVN.sh
        - exit
    environment:
        name: master
        url: 50.116.45.115:9090
    only:
        - master
